In [1]:
# 1.

import pandas as pd

ipl_df = pd.read_csv("ipl_matches.csv")

display(ipl_df.head(5))

     Match Team1 Team2 Winner
0  Match 1   CSK    MI    CSK
1  Match 2   RCB   KKR    KKR
2  Match 3    MI    GT     GT
3  Match 4   CSK   RCB    RCB
4  Match 5   KKR    MI     MI

In [3]:
ipl_df = ipl_df.dropna(subset=["Winner"])

ipl_df = ipl_df.reset_index(drop=True)

display(ipl_df)

     Match Team1 Team2 Winner
0  Match 1   CSK    MI    CSK
1  Match 2   RCB   KKR    KKR
2  Match 3    MI    GT     GT
3  Match 4   CSK   RCB    RCB
4  Match 5   KKR    MI     MI

In [5]:
# 3.

import pandas as pd
import numpy as np

data = {
    "Match": ["Match 1", "Match 2", "Match 3", "Match 4", "Match 5"],
    "Team1": ["CSK", "RCB", "MI", "CSK", "KKR"],
    "Team2": ["MI", "KKR", "GT", "RCB", "MI"],
    "Winner": ["CSK", "KKR", "GT", "RCB", "MI"],
    "win_by_runs": [20, 0, 0, 0, 15],
    "win_by_wickets": [0, 6, 7, 5, 0]
}

ipl_df = pd.DataFrame(data)

conditions = [
    ipl_df["win_by_runs"] > 0,
    ipl_df["win_by_wickets"] > 0
]

choices = ["Runs", "Wickets"]

ipl_df["match_margin_type"] = np.select(
    conditions,
    choices,
    default="Tie/No Result"
)
display(ipl_df)

     Match Team1 Team2 Winner  win_by_runs  win_by_wickets match_margin_type
0  Match 1   CSK    MI    CSK           20               0              Runs
1  Match 2   RCB   KKR    KKR            0               6           Wickets
2  Match 3    MI    GT     GT            0               7           Wickets
3  Match 4   CSK   RCB    RCB            0               5           Wickets
4  Match 5   KKR    MI     MI           15               0              Runs

In [6]:
# 4.

import pandas as pd

team_data = {
    "team": ["CSK", "MI", "RCB", "KKR", "GT"],
    "home_city": ["Chennai", "Mumbai", "Bangalore", "Kolkata", "Ahmedabad"]
}

team_df = pd.DataFrame(team_data)

ipl_df = ipl_df.merge(
    team_df,
    left_on="Team1",
    right_on="team",
    how="left"
)

ipl_df = ipl_df.rename(columns={"home_city": "Team1_Home_City"})

ipl_df = ipl_df.drop(columns=["team"])

ipl_df = ipl_df.merge(
    team_df,
    left_on="Team2",
    right_on="team",
    how="left"
)

ipl_df = ipl_df.rename(columns={"home_city": "Team2_Home_City"})

ipl_df = ipl_df.drop(columns=["team"])

display(ipl_df)

,Match,Team1,Team2,Winner,win_by_runs,win_by_wickets,match_margin_type,Team1_Home_City,Team2_Home_City
0,Match 1,CSK,MI,CSK,20,0,Runs,Chennai,Mumbai
1,Match 2,RCB,KKR,KKR,0,6,Wickets,Bangalore,Kolkata
2,Match 3,MI,GT,GT,0,7,Wickets,Mumbai,Ahmedabad
3,Match 4,CSK,RCB,RCB,0,5,Wickets,Chennai,Bangalore
4,Match 5,KKR,MI,MI,15,0,Runs,Kolkata,Mumbai

In [8]:
# 5.

import pandas as pd

ipl_df["Season"] = [2023, 2023, 2023, 2023, 2023]

pivot = pd.pivot_table(
    ipl_df,
    index="Winner",
    columns="Season",
    values="Match",
    aggfunc="count",
    fill_value=0
)

print("Total Matches Won by Each Team per Season:")
display(pivot)

top_3 = (
    pivot.stack()
    .reset_index(name="Wins")
    .sort_values("Wins", ascending=False)
    .head(3)
)

print("Top 3 Teams with Most Wins in a Single Season:")
display(top_3)

Total Matches Won by Each Team per Season:

Season  2023
Winner
CSK        1
GT         1
KKR        1
MI         1
RCB        1

Top 3 Teams with Most Wins in a Single Season:

  Winner  Season  Wins
0    CSK    2023     1
1     GT    2023     1
2    KKR    2023     1